{"name": "test_invalid_data[data2]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 210 == 400\n  +210\n  -400", "trace": "self = <test_api_creation.TestAPICreation object at 0x112f8fcd0>, api_client = <ApiClient(Thread-20, initial)>\ndata = {'email': 'invalid_passowd@mail.ru', 'password': '', 'username': 'invalid_pas'}\n\n    @pytest.mark.API\n    @pytest.mark.parametrize(\"data\", [data11, data21, data31, data41, data51, data61, data71])\n    def test_invalid_data(self, api_client, data):\n    \n        response = api_client.create(**data)\n>       assert response.status_code == 400\nE       assert 210 == 400\nE         +210\nE         -400\n\napi_client = <ApiClient(Thread-20, initial)>\ndata       = {'email': 'invalid_passowd@mail.ru', 'password': '', 'username': 'invalid_pas'}\nresponse   = <Response [210]>\nself       = <test_api_creation.TestAPICreation object at 0x112f8fcd0>\n\ntests/tests_api/test_api_creation.py:56: AssertionError"}, "parameters": [{"name": "data", "value": "{'username': 'invalid_pas', 'password': '', 'email': 'invalid_passowd@mail.ru'}"}], "start": 1589971077877, "stop": 1589971077914, "uuid": "3a1f22d5-e044-466b-abeb-51ee4fb596fd", "historyId": "1258cc7a345c7c79e8946a48ad2b33f4", "testCaseId": "0376a905d4248e62a552bb387e2a6e5e", "fullName": "tests.tests_api.test_api_creation.TestAPICreation#test_invalid_data", "labels": [{"name": "tag", "value": "API"}, {"name": "parentSuite", "value": "tests.tests_api"}, {"name": "suite", "value": "test_api_creation"}, {"name": "subSuite", "value": "TestAPICreation"}, {"name": "host", "value": "MacBook-Air-Mac.local"}, {"name": "thread", "value": "2637-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_api.test_api_creation"}]}