{"name": "test_invalid_data[data4]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 210 == 400\n  +210\n  -400", "trace": "self = <test_api_creation.TestAPICreation object at 0x112fcd9d0>, api_client = <ApiClient(Thread-22, initial)>\ndata = {'email': 'big_length_username@mail.ru', 'password': 'big_length_username_pas', 'username': 'very_big_length_username'}\n\n    @pytest.mark.API\n    @pytest.mark.parametrize(\"data\", [data11, data21, data31, data41, data51, data61, data71])\n    def test_invalid_data(self, api_client, data):\n    \n        response = api_client.create(**data)\n>       assert response.status_code == 400\nE       assert 210 == 400\nE         +210\nE         -400\n\napi_client = <ApiClient(Thread-22, initial)>\ndata       = {'email': 'big_length_username@mail.ru', 'password': 'big_length_username_pas', 'username': 'very_big_length_username'}\nresponse   = <Response [210]>\nself       = <test_api_creation.TestAPICreation object at 0x112fcd9d0>\n\ntests/tests_api/test_api_creation.py:56: AssertionError"}, "parameters": [{"name": "data", "value": "{'username': 'very_big_length_username', 'password': 'big_length_username_pas', 'email': 'big_length_username@mail.ru'}"}], "start": 1589971078241, "stop": 1589971078268, "uuid": "2210e134-7ee5-4416-9cd3-1c826d880216", "historyId": "888d7e9ca742662a956fe8771a13b3fc", "testCaseId": "0376a905d4248e62a552bb387e2a6e5e", "fullName": "tests.tests_api.test_api_creation.TestAPICreation#test_invalid_data", "labels": [{"name": "tag", "value": "API"}, {"name": "parentSuite", "value": "tests.tests_api"}, {"name": "suite", "value": "test_api_creation"}, {"name": "subSuite", "value": "TestAPICreation"}, {"name": "host", "value": "MacBook-Air-Mac.local"}, {"name": "thread", "value": "2637-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.tests_api.test_api_creation"}]}